CREATE DATABASE korkmaz_market;

USE korkmaz_market;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL
);

CREATE TABLE orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

INSERT INTO products (name, description, price) VALUES
('Ülker Çikolatalı Gofret', 'Lezzetli çikolatalı gofret', 6.00),
('Eti Hoşbeş', 'Çıtır çıtır gofret', 6.50),
('Ülker Metro', 'Lezzetli çikolata barı', 7.00),
('Eti Pop Kek', 'Meyveli kek', 8.00),
('Ülker Albeni', 'Karamelli çikolata', 7.50),
('Eti Cin', 'Portakal jöleli bisküvi', 4.50),
('Ülker Krispi', 'Tuzlu kraker', 5.00),
('Eti Puf', 'Marshmallowlu bisküvi', 4.75),
('Ülker Halley', 'Marshmallowlu kek', 9.00),
('Eti Burçak', 'Yulaflı bisküvi', 6.75),
('Ülker Dankek', 'Meyveli kek', 8.50),
('Eti Browni', 'Yoğun çikolatalı kek', 7.25),
('Ülker Çizi', 'Peynirli kraker', 5.25),
('Eti Tutku', 'Kakaolu bisküvi', 6.00),
('Ülker Rondo', 'Kakaolu bisküvi', 5.50),
('Eti Finger', 'Çikolata kaplı bisküvi', 7.50),
('Ülker Sütlü Çikolata', 'Sütlü çikolata barı', 10.00),
('Eti Çikolatalı Gofret', 'Çikolata kaplı gofret', 6.00),
('Ülker 9 Kat Tat', 'Kat kat gofret', 5.75),
('Eti Petibör', 'Klasik bisküvi', 4.00),
('Ülker Biskrem', 'Kakaolu kremalı bisküvi', 7.00),
('Eti Negro', 'Kakaolu kremalı bisküvi', 6.50),
('Ülker Hanımeller', 'Ev yapımı tarzı kurabiye', 8.25),
('Eti Form', 'Lifli bisküvi', 5.50),
('Ülker Kremalı Bisküvi', 'Vanilya kremalı bisküvi', 5.75),
('Eti Çikolata', 'Sütlü çikolata barı', 10.50),
('Ülker Smartt', 'Çikolata kaplı draje', 4.50),
('Eti Çubuk Kraker', 'Çubuk şeklinde kraker', 3.50),
('Ülker Hobby', 'Karamelli çikolata', 8.00),
('Eti Crax', 'Baharatlı çubuk kraker', 4.25),
('Nestle KitKat', 'Çikolatalı gofret', 10.00),
('Torku Banada', 'Fındık kremalı bisküvi', 7.00),
('Nestle Nesquik Bar', 'Sütlü çikolata ve tahıl barı', 12.00),
('Torku Kremalı Bisküvi', 'Kakaolu kremalı bisküvi', 5.50),
('Nestle Damak', 'Fıstıklı sütlü çikolata', 13.50),
('Torku Çokomilk', 'Çikolatalı sütlü bisküvi', 6.00),
('Nestle Chokella', 'Fındık kremalı gofret', 9.50),
('Torku Mini Gofret', 'Kakaolu gofret', 4.75),
('Nestle Bounty', 'Hindistan cevizli çikolata', 11.00),
('Torku Turtacık', 'Meyveli kek', 8.25),
('Nestle Lion', 'Çikolata kaplı karamel ve bisküvi', 10.50),
('Torku Baton Çikolata', 'Sütlü çikolata barı', 9.00),
('Nestle Chokito', 'Karamelli çikolata barı', 10.75),
('Torku Sütlü Çikolata', 'Sütlü çikolata', 7.50),
('Nestle Crunch', 'Çıtır pirinç patlaklı çikolata', 10.00),
('Torku Nugat', 'Fındıklı nugat', 8.50),
('Nestle Milkybar', 'Beyaz çikolata', 11.00),
('Torku Mozaik Pasta', 'Mozaik pasta dilimi', 8.75),
('Nestle Aero', 'Hava kabarcıklı sütlü çikolata', 10.00),
('Torku Karamelli Bar', 'Karamel dolgulu çikolata', 9.50),
('Nestle Nuts', 'Fındıklı sütlü çikolata', 11.50),
('Torku Çıtır Gofret', 'Kakaolu çıtır gofret', 6.75),
('Nestle KitKat Chunky', 'Büyük boy çikolatalı gofret', 12.00),
('Torku Fındık Kreması', 'Çikolata kaplı fındık kreması', 7.75),
('Nestle Fitness Bar', 'Tahıl barı', 9.50),
('Torku Pekmezli Kurabiye', 'Pekmezli kurabiye', 8.00),
('Nestle Golden Grahams Bar', 'Sütlü tahıl barı', 12.00),
('Torku Pekmezli Bisküvi', 'Pekmezli bisküvi', 7.00),
('Nestle Corn Flakes Bar', 'Mısır gevreği barı', 11.50),
('Torku Fıstıklı Gofret', 'Fıstıklı gofret', 6.50),
('Nestle Cheerios Bar', 'Yulaf barı', 10.50),
('Torku Kakaolu Bar', 'Kakaolu fındık kremalı bar', 7.75),
('Nestle Smarties', 'Renkli şeker kaplı çikolata', 8.50),
('Torku Biskrem', 'Çikolatalı kremalı bisküvi', 7.00),
('Nestle After Eight', 'Naneli bitter çikolata', 14.00),
('Torku Naneli Gofret', 'Naneli gofret', 6.50),
('Nestle Rolo', 'Karamel dolgulu çikolata', 11.00),
('Torku Karamelli Kurabiye', 'Karamelli kurabiye', 8.00),
('Nestle KitKat Senses', 'Fındıklı çikolatalı gofret', 12.50),
('Torku Pekmezli Kek', 'Pekmezli kek', 8.50),
('Nestle Toffee Crisp', 'Karamel ve çıtır pirinç barı', 10.75),
('Torku Çikolata Kaplı Fındık', 'Çikolata kaplı fındık', 9.00),
('Nestle Quality Street', 'Karışık çikolatalar', 18.00),
('Torku Çokodamla', 'Damla çikolatalı bisküvi', 8.75),
('Nestle KitKat Zebra', 'Çizgili çikolatalı gofret', 13.00),
('Torku Şekerli Gofret', 'Şeker kaplı gofret', 5.75),
('Nestle Milkybar Buttons', 'Beyaz çikolata düğmeleri', 9.00),
('Torku Fındıklı Çikolata', 'Fındıklı sütlü çikolata', 8.50),
('Nestle Caramac', 'Karamelli çikolata', 11.50),
('Torku Beyaz Çikolata', 'Beyaz çikolata barı', 7.00),
('Nestle Walnut Whip', 'Cevizli çikolata', 12.00),
('Torku Fıstıklı Çikolata', 'Fıstıklı sütlü çikolata', 9.00),
('Nestle Yorkie', 'Çikolatalı bar', 10.75),
('Torku Karamelli Gofret', 'Karamel dolgulu gofret', 7.50),
('Nestle Milkybar Raisins', 'Kuru üzümlü beyaz çikolata', 10.00),
('Torku Portakallı Kurabiye', 'Portakal aromalı kurabiye', 8.00);
